### PR TITLE
Expose IMEI type, representing a valid IMEI

### PR DESCRIPTION
**Pull request by hdoordt**

### CODE REVIEW

**Comment by hdoordt** [comment]
@grantshandy are you available for reviewing this PR some time?

**Comment by grantshandy** [comment]
If this is what you need from this crate, then I'll pull it in. Looks good 👍🏽

**Comment by grantshandy** [comment]
@hdoordt  https://crates.io/crates/imei/1.1.0 <-- here you are

**Comment by hdoordt** [comment]
Great, thanks!

**Pull request merged**
